### ISSUE TITLE
Problems with static

### ISSUE THREAD

**Issue by mke21** [galaxy-genome-annotation/docker-jbrowse#2]
Hi,

When running this docker, I get a 404 error on static content like /src/dojo/dojo.js

This means that jbrowse is not working, giving a white page. This is only when I build it from this repo, the image in the Docker hub works fine.

**Comment by hexylena** [comment]
Hi @mke21. I'm sorry you're hitting this issue.

I'm not sure when I'll be able to look at it (Galaxy/GMOD conference this week). I'll be able to get back to this in about 2 weeks, unless I can find time sooner.

**Comment by mke21** [comment]
Okay, thanks!

**Comment by hexylena** [comment]
@mke21 is this still an issue? I've tested locally (`docker-compose build && docker-compose up`) and it seems to be functional now.
