### ISSUE TITLE
Digest::Crc32 missing ?

### ISSUE THREAD

**Issue by sletort** [galaxy-genome-annotation/docker-jbrowse#5]
When using Jbrowse with docker, I needed to install Digest::Crc32 with cpan to use prepare-refseqs.pl.

```
$ docker run -v myData:/data/refData -it -p 80:80 --entrypoint=/bin/bash jbrowse/jbrowse-1.12.0
$ prepare-refseqs.pl --fasta /data/refData/Brassica_napus_v4.1.chromosomes.fasta
Can't locate Digest/Crc32.pm in @INC [...]
$ cpan install Digest::Crc32
$ prepare-refseqs.pl --fasta /data/refData/Brassica_napus_v4.1.chromosomes.fasta

```

**Comment by abretaud** [comment]
Thanks Sébastien, it should be fixed with 7bf5da8
Can you test when the new image is built on https://hub.docker.com/r/erasche/jbrowse/builds/ ?

**Comment by sletort** [comment]
Another package is missing : Bio::GFF3::LowLevel::Parser
when using flatfile-to-json.pl

**Comment by abretaud** [comment]
Ok, done too

**Comment by sletort** [comment]
Merci.
Another package is missing for a better lisibility of help : perl-doc (with apt-get).

**Comment by abretaud** [comment]
Done too !

**Comment by hexylena** [comment]
Thanks @abretaud, appreciate all the help!
