### ISSUE TITLE
1.12.3 tag

### ISSUE THREAD

**Issue by abretaud** [galaxy-genome-annotation/docker-jbrowse#6]
Hey,
I have just update the dockerfile for the 1.12.3 version, would it be possible to add the corresponding tags at hub.docker.com?

**Comment by hexylena** [comment]
Absolutely! Sorry, I'd stopped paying attention to this once the jbrowse devs took over the gmod/jbrowse image (and then failed to make it automatic)

**Comment by hexylena** [comment]
https://quay.io/repository/erasche/jbrowse I've added a quay.io build since they're not a horrible service like docker hub and will build on all tags.

**Comment by abretaud** [comment]
Great, thanks!
