### ISSUE TITLE
Volvox sample data incompletely configured?

### ISSUE THREAD

**Issue by RichardBruskiewich** [galaxy-genome-annotation/docker-jbrowse#8]
Small cosmetic issue, but some of the tracks in the sample Volvox data seem misconfigured, although I think that (most) such data is sitting in the example data directory of the project.  

![docker-jbrowse-config-error](https://user-images.githubusercontent.com/401246/48086807-95e45e80-e1b2-11e8-855b-abe55a0b5220.png)

I know that this is more of a jbrowse (not docker-jbrowse) issue but perhaps fixing this data "bug" is useful to "green" users of the docker-jbrowse container.

I know that you have already posted some basic instructions in the project README about loading user data into the instance, but just in case, you may wish to point users (via links) to additional **jbrowse** documentation about the loading scripts listed, i.e.

    prepare-refseqs.pl
    biodb-to-json.pl
    add-json.pl
    generate-names.pl

**Comment by abretaud** [comment]
Thanks for reporting! It's fixed now (docker image is building at the moment)
